Fix a bug in handling ibmcloud_api_key
ibm-hyper-protect/linuxone-vsi-automation-samples pull request #20
Opened 2022-09-14 10:59 UTC by vishwabmc

Fixes: https://github.com/ibm-hyper-protect/linuxone-vsi-automation-samples/issues/19

Signed-off-by: vishwabmc <vishwanath@in.ibm.com>

2022-09-14 11:59 UTC, CarstenLeue requested changes

2022-09-14 11:59 UTC, CarstenLeue commented on terraform-hpvs/hello-world/terraform.tf
> +  ibmcloud_api_key = var.ibmcloud_api_key
I prefer to have the api key in the environment variable, that's why it's not on this level

2022-09-14 13:01 UTC, vishwabmc commented on terraform-hpvs/hello-world/terraform.tf
> +  ibmcloud_api_key = var.ibmcloud_api_key
okay ?. But then how do we resolve the bug #19 ?

2022-09-15 14:15 UTC, CarstenLeue commented on terraform-hpvs/hello-world/terraform.tf
> +  ibmcloud_api_key = var.ibmcloud_api_key
I guess we need to fix the documentation stating that we pass this via the tfvars file. 

To be honest the many different ways how to configure the provider are really confusing, it's hard to tell conceptually when to use what.

In my mental model you would pass credentials such as the API key in environment variables, not in files. Think of a CICD system, you want these credentials to be injected by the CICD provider (e.g. a Jenkins credential). You in particular do not want to persist this.

The other values such as region and zone are rather configuration aspects, they perfectly make sense in a config file.

2022-09-16 05:53 UTC, vishwabmc commented on terraform-hpvs/hello-world/terraform.tf
> +  ibmcloud_api_key = var.ibmcloud_api_key
Okay.. If we are going in that direction, we need to remove `ibmcloud_apikey` from `auto.tfvars-template` file and ask user to set either `TF_VAR_ibmcloud_api_key` or `IC_API_KEY`. If you ask me, I would not give multiple ways to configure as that leads to confusion.

2022-09-19 04:35 UTC, anunezde commented on terraform-hpvs/hello-world/terraform.tf
> +  ibmcloud_api_key = var.ibmcloud_api_key
My use case for having it in the config is that I have multiple accounts (and therefore keys) so having it in the config file allows me to avoid having to switch an env variable to select the right one. On the other side I see the point of the env variables for pipelines or for calling from a script.

Can we make it so that `ibmcloud_api_key` is only set if `var.ibmcloud_api_key` is not empty (set by the user in tfvars)?

2022-09-19 11:05 UTC, closed without merging