fix: acpi error for ubuntu 24.04 host
ibm-hyper-protect/linuxone-vsi-automation-samples pull request #76
Opened 2024-10-08 16:29 UTC by Sashwat-K

The on prem terraform example is failing on Ubuntu 24.04 host. The error is as follows

```
libvirt_domain.sashwatk_onprem_compose_domain: Still creating... [20s elapsed]
╷
│ Error: error defining libvirt domain: unsupported configuration: machine type 's390-ccw-virtio-noble' does not support ACPI
│ 
│   with libvirt_domain.sashwatk_onprem_compose_domain,
│   on terraform.tf line 160, in resource "libvirt_domain" "sashwatk_onprem_compose_domain":
│  160: resource "libvirt_domain" "sashwatk_onprem_compose_domain" {
│ 
╵
```

The error can be fixed by adding `<xsl:template match="acpi"/>` to the `domain_update.xsl` file. This PR updates the `domain_update.xsl` and readme with the relevant information.

This change has been tested in Ubuntu 24.04 and RHEL 8.8. The results show that the libvirt terraform provider is able to create HPVS instances.

2024-10-08 16:43 UTC, Timo-1 requested changes
This sentence is rather hard to understand due to punctuation.
Can it be rephrased, e.g.
Note: If the `terraform apply` is failing with the following error, add line `<xsl:template match="acpi"/>` to file `domain_update.xsl` file (File `domain_update.xsl` [add link!] has been updated with this change, see this file for reference).

2024-10-08 17:29 UTC, Sashwat-K commented
Hello @Timo-1 , I have updated the PR as per your review comments.

2024-10-09 06:10 UTC, Sativarsainath-26 approved these changes
Looks good to me.

2024-10-09 08:24 UTC, pranjank approved these changes

2024-10-09 10:10 UTC, Timo-1 approved these changes
LGTM - Thanks

2024-10-09 10:10 UTC, merged