Hello World Sample for HPCR
ibm-hyper-protect/linuxone-vsi-automation-samples pull request #9
Opened 2022-07-26 20:55 UTC by CarstenLeue

2022-07-26 21:22 UTC, angelnu requested changes
Just a few changes - largest one renaming the top folder to be short

2022-07-26 21:22 UTC, angelnu commented on hyper-protect-container-runtime/README.md
> +## IBM Cloud Hyper Protect Virtual Server for IBM Cloud VPC Examples
please use `terraform-hpvs` as name to be similar to the other samples. Also because HPVS is our official product name.

2022-07-26 21:22 UTC, angelnu commented on hyper-protect-container-runtime/hello-world/terraform.tf
> +  profile = "bz2e-1x4"
Have as var but not in the tfvars teample as most people do not need to change it

2022-07-26 21:22 UTC, angelnu commented on hyper-protect-container-runtime/hello-world/terraform.tf
> +  tags = ["hpcr", "sample", var.PREFIX]
should this be a var as well?

2022-07-27 07:10 UTC, CarstenLeue commented on hyper-protect-container-runtime/README.md
> +## IBM Cloud Hyper Protect Virtual Server for IBM Cloud VPC Examples
I assume you are referring to the folder name

2022-07-27 07:11 UTC, CarstenLeue commented on hyper-protect-container-runtime/hello-world/terraform.tf
> +  tags = ["hpcr", "sample", var.PREFIX]
Since this is just an example I would keep it as is. The reason to make the prefix configurable is that all resources use the prefix in their name and that could result in a clash. But not with tags.

2022-07-27 07:12 UTC, CarstenLeue commented on hyper-protect-container-runtime/hello-world/terraform.tf
> +  profile = "bz2e-1x4"
I'll add it as a var.

2022-07-27 15:32 UTC, anunezde approved these changes
Thanks for the contribution!

2022-07-27 15:32 UTC, merged